---

- hosts: 
  vars:
    home: /home/ec2-user
  tasks:

  - name: debug variable
    debug: var=home

  - name: creating file
    file:
      path: "{{ home }}/test-ansible"
      state: directory 
    register: task1

  - name: debugging task output
    debug: 

